[build]
  command = "npm run build"
  publish = ".next"
  environment = { SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_FIREBASE_API_KEY,NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,NEXT_PUBLIC_FIREBASE_PROJECT_ID,NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,NEXT_PUBLIC_FIREBASE_APP_ID,NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,NEXT_PUBLIC_STRIPE_PRICE_ESSENTIAL,NEXT_PUBLIC_STRIPE_PRICE_PRO,NEXT_PUBLIC_STRIPE_PRICE_SCALE,FIREBASE_ADMIN_PROJECT_ID" }

[[plugins]]
package = "@netlify/plugin-nextjs"